### ISSUE TITLE
OpenPop.Mime.Message.ToMailMessage() attachment name parsing bug

### ISSUE THREAD

**Issue by th3j0k3r** [foens/hpop#15]
Hi,

I have found a bug when receiving emails from live.com, hotmail.com, windowslive.com, etc. with attachments in it. I'm not sure that the attachment name parsing is wrong on your side, I think it is the error of the mailing system (http://forum.rebex.net/questions/2948/imap-an-attachment-s-filename-is-empty-for-mails-sent-from-hotmail).

I found a quick workaround for that, but I don't want to work with an "unofficial" version of your library. My workaround for OpenPop.Mime.Message.ToMailMessage is to add a null checking logic when you are iterating over the attachments, and if it fails then use the FileName property as a fallback. 
In code:

 // Add attachments to the message
            IEnumerable<MessagePart> attachments = FindAllAttachments();
            foreach (MessagePart attachmentMessagePart in attachments)
            {
                MemoryStream stream = new MemoryStream(attachmentMessagePart.Body);
                if (string.IsNullOrEmpty(attachmentMessagePart.ContentType.Name))
                {
                    attachmentMessagePart.ContentType.Name = attachmentMessagePart.FileName;
                }
                Attachment attachment = new Attachment(stream, attachmentMessagePart.ContentType);
                attachment.ContentId = attachmentMessagePart.ContentId;
                message.Attachments.Add(attachment);
            }

Hope this issue helps you guys to make your library more robust. If you have any question, please let me know, I am happy to help.

Imre Fodi,

**Comment by marcosbrigante** [comment]
There is indeed a problem with attachment names when calling ToMailMessage(). Unfortunately, I could not track it down as it happened only on my production server (it worked on my machine =P ). 
When the attachment name contained a word with an accent ("ê" on my case) and a space after it, the name of the attachment became the string below (obtained from my production log file):

"=?utf-8?B?RkQwOTM0MjE1OTAwMDE2OV8yMDE1MDEyM18yMDE1MDEyMzA0MDE0NV9J?= =?utf-8?B?QklVTkEgUFJFVklEw4pOQ0lBIEZJQ0ZJTS5YTUw=?="

When I saw this open issue here on github I removed ToMailMessage calls, then it worked perfectly.

Please contact me if you want more information about my environment.
