### ISSUE TITLE
 System.FormatException in System.Net.Mime.ContentType.set_MediaType( "Content-Transfer-Encoding: 8bit")

### ISSUE THREAD

**Issue by giammin** [foens/hpop#21]
System.FormatException: The specified content type is invalid.
   in System.Net.Mime.ContentType.set_MediaType(String value)
   in OpenPop.Mime.Header.HeaderFieldParser.ParseContentType(String headerValue)
   in OpenPop.Mime.Header.MessageHeader.ParseHeader(String headerName, String headerValue)
   in OpenPop.Mime.Header.MessageHeader.ParseHeaders(NameValueCollection headers)
   in OpenPop.Mime.Header.HeaderExtractor.ExtractHeadersAndBody(Byte[] fullRawMessage, MessageHeader& headers, Byte[]& body)
   in OpenPop.Mime.MessagePart.ParseMultiPartBody(Byte[] rawBody)
   in OpenPop.Mime.Message..ctor(Byte[] rawMessageContent, Boolean parseBody)
   in OpenPop.Pop3.Pop3Client.GetMessage(Int32 messageNumber)

Rawmessage:

Return-Path: <>
Delivered-To: myname.musurname@domain.it
Received: (qmail 9763 invoked by uid 89); 2 Oct 2012 08:16:56 -0000
Received: from unknown (HELO mySmtp.it) (xxx.xxx.xxx.xxx)
  by mysmtpdomain.it with SMTP; 2 Oct 2012 08:16:56 -0000
Received: from mysmtpdomain.it ([xxx.xxx.xxx.xxx])
	by mysmtpdomain.it with bizsmtp
	id 68EM1k05D4zqQwW018Gwjd; Tue, 02 Oct 2012 10:16:56 +0200
Date: Tue, 02 Oct 2012 10:16:56 +0200
From: Mail Delivery System <mail-daemon@mysmtpdomain.it>
To: myname.musurname@domain.it
Subject: Delivery status notification
MIME-Version: 1.0
Content-Type: multipart/report;
	boundary="------------I305M09060309060P_940813491658160"
X-Spam-Rating: mxavas4.ad.mysmtp.it 1.6.2 0/1000/N
X-Antivirus: AVG for E-mail 2013.0.3426 [3629/6880]
X-AVG-ID: ID27CD4F68-673CDD3B

This is a multi-part message in MIME format.

--------------I305M09060309060P_940813491658160
Content-Type: text/plain; charset=UTF-8;
Content-Transfer-Encoding: 8bit

      This is an automatically generated Delivery Status Notification.      

Delivery to the following recipients was aborted after 0 second(s):

  * destinationName.destinationSurname@domain.it

--------------I305M09060309060P_940813491658160
Content-Type: message/delivery-status; charset=UTF-8;
Content-Transfer-Encoding: 8bit

Reporting-MTA: dns; mySmtpDomain.it [xxx.xxx.xxx.xxx]
Received-From-MTA: dns; myHost.myDomain.it [xxx.xxx.xxx.xxx]
Arrival-Date: Tue, 02 Oct 2012 10:16:56 +0200

Final-recipient: rfc822; destinationName.destinationSurname@domain.it
Action: failed
Status: 5.1.1
Diagnostic-Code: smtp; 553 5.1.1 sorry, no mailbox here by that name.
Last-attempt-Date: Tue, 02 Oct 2012 10:16:56 +0200

--------------I305M09060309060P_940813491658160
Content-Type: text/rfc822-headers; Content-Transfer-Encoding: 8bit
Content-Disposition: attachment

X-Mailer: QUALCOMM Windows Eudora Version 7.1.0.9
Date: Tue, 02 Oct 2012 10:16:29 +0200
To: destinationName.destinationSurname@domain.it,othername.othersurname@domain.it
From: ME <name.surname@domain.it>
Subject: xxxxxxxxxxxxxxxxxxxxxxxxx
Mime-Version: 1.0
Content-Type: multipart/mixed;
	boundary="=====================_888953554==_"

--------------I305M09060309060P_940813491658160--

**Comment by JoshKeegan** [comment]
Can we close this? It should have been fixed by 72231d0e18315e67bafe790aa08779598a1f2cac.

**Comment by topazo** [comment]
I also encountered this exception "The specified media type is invalid". Unfortunately I don't have the email anymore. Also tried with latest fix of 72231d0 and the error exception message changed to: "Media Type must be in the format type / subtype". So apparently the header was somehow totally broken.  Any advise how to properly recognize and handle this kind of situation - or should hpop maybe fallback to some content type if anything else fails?

**Comment by JoshKeegan** [comment]
@topazo The new more specific exception that you've got is because the media type didn't contain a '/' character, which is used to separate the type and subtype.

If it happens again, can you post the media type?
I don't think there's much we could do here without guessing what the sender intended, but it is *possible* that the media type is in some sort of non-standard format that we still could work with.

**Comment by giammin** [comment]
the raw message i posted on 1 post should raise the exception. now i don't have time to test

**Comment by topazo** [comment]
@JoshKeegan we encountered this same problem again (spam e-mail). Header has value:
Content-Type: text/html;iso-8859-1
This was also the case last time. I guess problem is that latter part of the field doesn't have keyword "charset=" in it. Is this something that you can fix in hpop core or can you give advise how to handle the exception properly so that we can recognize and skip such email?

**Comment by giammin** [comment]
i did this edit and it works fine:

     public static ContentType ParseContentType(string headerValue)
		{
			if(headerValue == null)
				throw new ArgumentNullException("headerValue");

			// We create an empty Content-Type which we will fill in when we see the values
			ContentType contentType = new ContentType();

			// Now decode the parameters
			List<KeyValuePair<string, string>> parameters = Rfc2231Decoder.Decode(headerValue);

			foreach (KeyValuePair<string, string> keyValuePair in parameters)
			{
				string key = keyValuePair.Key.ToUpperInvariant().Trim();
				string value = Utility.RemoveQuotesIfAny(keyValuePair.Value.Trim());
			    try
			    {
			        switch (key)
			        {
			            case "":
			                // This is the MediaType - it has no key since it is the first one mentioned in the
			                // headerValue and has no = in it.

			                // Check for illegal content-type
			                string v = value.ToUpperInvariant();
                            if (v.Equals("TEXT") || v.Equals("TEXT/"))
			                    value = "text/plain";
                            //hack: temp hack
                            try
                            {
                                contentType.MediaType = value;
                            }
                            catch
                            {
                                try
                                {
                                    contentType.MediaType = value.Replace(" ", string.Empty);
                                }
                                catch
                                {
                                    contentType.MediaType = "text/plain";
                                }
                            }
			                break;

			            case "BOUNDARY":
			                contentType.Boundary = value;
			                break;

			            case "CHARSET":
			                contentType.CharSet = value;
			                break;

			            case "NAME":
			                contentType.Name = EncodedWord.Decode(value);
			                break;

			            default:
			                // This is to shut up the code help that is saying that contentType.Parameters
			                // can be null - which it cant!
			                if(contentType.Parameters == null)
			                    throw new Exception("The ContentType parameters property is null. This will never be thrown.");

			                // We add the unknown value to our parameters list
			                // "Known" unknown values are:
			                // - title
			                // - report-type
			                contentType.Parameters.Add(key, value);
			                break;
			        }
			    }
			    catch (Exception e)
			    {
                    throw new ArgumentOutOfRangeException(string.Format("cannot parse header:{0}", headerValue), e);
			    }
			}

			return contentType;
		}

**Comment by JoshKeegan** [comment]
@topazo because the second part (iso-8859-1) has no key, it is treating that as the media type, so it tries to parse it as such, even though we already have a media type.
This should be an easy fix, I'll have it ignore later entries without a key. The downside to doing that is that we wouldn't parse out the charset from the example you've posted, but I wouldn't want to assume that later entries without a key will always be the charset as they could just as easily be other stuff.

@giammin Your issue should be fixed in the latest release on NuGet, the issue @topazo is having is separate, although also with content type parsing. 
If @topazo were to use your code for his example, the content type of the message would get treated as "text/plain" without warning, so I wouldn't recommend doing so unless you know that having the wrong content type is acceptable for you.

**Comment by fedlerner** [comment]
Hi,

I seem to be having the same issue that was reported on the past when executing GetMessage(i).
I have the latest version of OpenPop.NET installed via NuGet (v2.0.6.1120).

This is the error I'm getting:

> No se controló System.FormatException
>   HResult=-2146233033
>   Message=La entrada no es una cadena Base 64 válida porque contiene un carácter que no es Base 64, más de dos caracteres de relleno o un carácter no válido entre los caracteres de relleno. 
>   Source=mscorlib
>   StackTrace:
>        en System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
>        en System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
>        en System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
>        en System.Security.Cryptography.FromBase64Transform.TransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
>        en OpenPop.Mime.Decode.Base64.Decode(String base64Encoded)
>        en OpenPop.Mime.MessagePart.ParseBody(Byte[] rawBody)
>        en OpenPop.Mime.MessagePart.ParseMultiPartBody(Byte[] rawBody)
>        en OpenPop.Pop3.Pop3Client.GetMessage(Int32 messageNumber, IParsingErrorHandler parsingErrorHandler)
>        en DescargarGmail.Program.DescargarMensajes(String hostname, Int32 port, Boolean useSsl, String username, String password, String path) en C:\Develop\DescargarGmail\DescargarGmail\Program.cs:línea 119
>        en DescargarGmail.Program.Main(String[] args) en C:\Develop\DescargarGmail\DescargarGmail\Program.cs:línea 36
>        en System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>        en System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>        en Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>        en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>        en System.Threading.ThreadHelper.ThreadStart()
>   InnerException: 

Is there any solution for this issue ? Please let me know if I should provide more information..
