### ISSUE TITLE
add address to  mailMessage.Headers.To

### ISSUE THREAD

**Issue by mey2021** [foens/hpop#22]
hi 
i need add  recipient  to header to collection but constractor RfcMailAddress class is private
any method or advise?

Thank you

**Comment by ruffin--** [comment]
Is "inspection only" going to stay a hard and fast rule in the future? I was using OpenPop to pull messages for a client, but wanted to serialize System.Net.Mail.MailMessages to a file before I send them. There's some discussion about [doing this through reflectance here on StackOverflow](http://stackoverflow.com/questions/7515457), which worked fine on Windows, but that's a little dirty, might have had some breaking changes recently, and doesn't work as-is on MonoMac. 

Reviewing that SO question today, I saw a [new post from Jeffrey Steadfast](http://stackoverflow.com/a/22024114/1028230), the MimeKit guy, who did the only other thing I could think of doing -- [mapping MailMessage by hand to an existing mime message structure](https://github.com/jstedfast/MimeKit/blob/1ea79dddc1a1dd96890e2f3fe2395232f8165a4c/MimeKit/MimeMessage.cs#L1951).

I was considering doing the same thing with an extension method for OpenPop.Mime.Message, but that's impossible to do with the current "mental model".

Nothing wrong with that, of course. It makes some sense to add the serialization function directly to System.Net.Mail.MailMessages instead (without reflection). That would keep separation of concerns pretty rigid, which is potentially A Good Thing.

2¢, etc.

(Would've posted to the mailing list to discuss, but that's kaput, obviously. Thanks for the library; it's been very good to me up until this point!)

**Comment by foens** [comment]
Well, at the moment I am not actively working on OpenPop. If you would like to take over and keep OpenPop going, that is fine by me. Then you can of course decide what the future would bring for OpenPop. MimeKit seems to be a very good library, maybe OpenPop has been overtaken, and you should use MimeKit?
