### ISSUE TITLE
Accented characters from UTF-8 attachments are converted to ??

### ISSUE THREAD

**Issue by kobruleht** [foens/hpop#26]
Steps to reproduce:

Use this code to read UTF-8 encoded attachment:

    using (OpenPop.Pop3.Pop3Client client = new Pop3Client())
    {
        client.Connect("mail.company.com", 110, false);
        client.Authenticate("user", "pass", AuthenticationMethod.UsernameAndPassword);
        if (client.Connected)
        {
            int messageCount = client.GetMessageCount();
            List<Message> allMessages = new List<Message>(messageCount);
            for (int i = messageCount; i > 0; i--)
            {
                var msg = client.GetMessage(i);
                var att = msg.FindAllAttachments(); 
                foreach (var ado in att)
                {
                    var xml = ado.GetBodyAsText();

In result xml string accented characters are converted to tow ?? marks.
`XXXLTEC O=C3=9C` in message below appears as `XXXLTEC O??` in xml variable.
Correct result is `XXXLTEC OÜ`

Sample XML Attachment in message:

    ------=_NextPart_000_0066_01D0302C.83D6EFA0
    Content-Type: text/xml;
    	name="tapitolemas.xml"
    Content-Transfer-Encoding: quoted-printable
    Content-Disposition: attachment;
    	filename="tapitolemas.xml"
    
    <?xml version=3D"1.0" encoding=3D"UTF-8"?>
    <E-Document>
      <Header>
        <DateIssued>2015-01-02T13:27</DateIssued>
        <SenderID>-</SenderID>
        <ReceiverID>1COL</ReceiverID>
      </Header>
      <Document>
        <DocumentType>invoice</DocumentType>
        <DocumentFunction>original</DocumentFunction>
        <DocumentParties>
          <BuyerParty context=3D"partner">
            <PartyCode>1COL</PartyCode>
            <Name>XXXLTEC O=C3=9C</Name>

Posted also in https://stackoverflow.com/questions/27949470/how-to-read-utf-8-mail-attachments-from-pop3

**Comment by foens** [comment]
I suspect that OpenPop assumes US-ASCII as encoding, since no encoding is specified in the Content-Type. OpenPop does not try to guess the encoding if not specifies, [it defaults to US-ASCII](https://github.com/foens/hpop/blob/master/OpenPop/Mime/Header/MessageHeader.cs#L262). Not sure if this is specified in an RFC anywhere.

Most XML documents are UTF, and it also says so in the first line. However, OpenPop does not inspect the contents of an attachment, but only looks at the MIME headers. If this is general for your application, you could decode the bytes to a string yourself, using the correct encoding.

**Comment by kobruleht** [comment]
This can fixed by changing in MessagePrt.cs GetBodyAsText() method to

		public string GetBodyAsText()
		{
            return Encoding.UTF8.GetString(Body);
            // Original gets ?? characters instead of unicode ones
            //return BodyEncoding.GetString(Body);
		}

How to change OpenPop so this can used without changing source code ?

**Comment by foens** [comment]
Your changes would destroy any attachment which does not use UTF-8. Instead, you should convert the raw bytes yourself:
```c#
MessagePart m = ...; // Get the message part somehow
string text = Encoding.UTF8.GetString(m.Body);
```
In that way, you do not have to change OpenPop.

**Comment by kobruleht** [comment]
Shoud line in sample code

                            var xml = ado.GetBodyAsText();

changed to 
                            var xml = Encoding.UTF8.GetString(ado.Body);
?

**Comment by foens** [comment]
Yes
