### ISSUE TITLE
not works for gmail, what should do for?

### ISSUE THREAD

**Issue by Tinario** [foens/hpop#39]
Pop3Client pop3Client = new Pop3Client();
try
            {
                pop3Client.Connect("pop.gmail.com", 995, true);
                pop3Client.Authenticate("email", "password");
                pop3Client.Disconnect();
                return true;
            }
            catch (OpenPop.Pop3.Exceptions.InvalidLoginException ex)
            {
                MessageBox.Show(ex.Message + "\nPlease take a look at \"Email\" and \"Password\" fields, verify if both are correct.");
                return false;
            }

i tried for microsoft hotmail and works perfectly, but for gmail give me exception "Server did not accept user credentials", but the credentials are correct, i logged manually on browser to see if is correct.
what should i do?

**Comment by foens** [comment]
Do you have pop3 enabled for your account?

**Comment by Tinario** [comment]
yes, i actived it on gmail configuration / Forwarding and POP/IMAP

**Comment by foens** [comment]
Strange. I know there are many that are using Gmail. Could it be that the
password or account contains non ascii characters?

**Comment by Tinario** [comment]
i think not, bcz i tried with a normal email and password too, without non ascii characters

**Comment by Tinario** [comment]
finally i found the solution, and i will describe here.
1-enable the pop at Configurations / Forwarding and POP/IMAP
2- follow this link: https://www.google.com/settings/security/lesssecureapps
and activate for less secure apps.

thank you so much foens, have a nice day.

**Comment by foens** [comment]
You too - glad you found a solution.

**Comment by migueltadeo** [comment]
Thanks for this solution, I had the same problem and I solved folowing the link that you sent and turn off this option.

**Comment by migueltadeo** [comment]
Thanks for this solution, I had the same problem and I solved folowing the link that you sent and turn on this option.

**Comment by migueltadeo** [comment]
Thanks for this solution, I had the same problem and I solved it following the link that you sent and pressing the "turn on" option.

**Comment by JaveriaNasir** [comment]
Hey friends,

I have a quick question. Even i faced the same problem for getting authenticated to gmail service account using POP3. I followed the instructions said above and was able to authenticate successfully. But i have a question like since we made the security for gmail service account as less secure. Does it impact any way?? or is there any drawbacks or something? please clarify my doubt. Help will be greatly appreciated.

Thanks
**Javeria Nasir**

**Comment by foens** [comment]
Is it less secure because you enabled POP3?

**Comment by JaveriaNasir** [comment]
Yeah I am using POP3

**Comment by techyrajput** [comment]
Hey friends, 
I am facing issue when I am trying to connect the Businss microsoft which ends with domain name (abc@abc.com). I am getting these error "ERR Logon failure: unknown user name or bad password." "Server did not accept user credentials" in the authenticate method. When I am trying to access email by using same credentials then I am able to login.

![image](https://user-images.githubusercontent.com/24393947/82454046-f0ac8500-9ace-11ea-8a72-8e5567312293.png)
I am using the Pop3client to connect with outlook.office.com server and port number 995. 
Is there any setting in the microsoft mail to allow less secure apps.
Thanks 
Ashish Rajput
