### ISSUE TITLE
Identify "real" attachments

### ISSUE THREAD

**Issue by hebrao** [foens/hpop#45]
Is there any way to identify real Attachements vs Embedded Resources (like signature images, etc)?
I have to download only attached files, like XLS, PDF, etc.

Tks!

**Comment by foens** [comment]
I am not sure how other email clients do that. However, there is a Content-Disposition, which can specify 'attachment' or 'inline'. I would think that signatures and other content that is shown together with the message should have 'inline' specified and real attachents should have 'attachment' specified. You might also be able to use the filename, if you only need to find a specific set of file types.
