### ISSUE TITLE
Does not retrieve all email

### ISSUE THREAD

**Issue by sqlguy6212** [foens/hpop#56]
I have used the code provided in examples but I get only emails from before 2015.  Since the emails I would be interested in are current this makes this library fairly useless.

**Comment by foens** [comment]
I guess you are using Gmail, and they filter in what messages they return to reduce bandwidth requirements for their servers. You should search for a solution using your favorite search engine, or see http://stackoverflow.com/questions/31964593/gmail-pop3-not-getting-all-messages-in-java-application
